use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailVerifyConfig {
    pub emails: Vec<String>,
    pub timeout: u64,
    pub check_smtp: bool,
    pub check_format: bool,
    pub check_spf: bool,
    pub check_dkim: bool,
    pub check_dmarc: bool,
    pub check_breach: bool,
}

impl Default for EmailVerifyConfig {
    fn default() -> Self {
        Self {
            emails: vec![],
            timeout: 10,
            check_smtp: true,
            check_format: true,
            check_spf: true,
            check_dkim: false,
            check_dmarc: true,
            check_breach: false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailVerifyResult {
    pub results: Vec<EmailVerifyEntry>,
    pub total_checked: usize,
    pub valid_count: usize,
    pub invalid_count: usize,
    pub risky_count: usize,
    pub summary: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmailVerifyEntry {
    pub email: String,
    pub local_part: String,
    pub domain: String,
    pub is_valid_format: bool,
    pub mx_records_found: bool,
    pub mx_records: Vec<String>,
    pub smtp_reachable: Option<bool>,
    pub is_disposable: bool,
    pub is_role_account: bool,
    pub is_catch_all: Option<bool>,
    pub spf_record: Option<String>,
    pub dkim_record: Option<String>,
    pub dmarc_record: Option<String>,
    pub breach_count: Option<usize>,
    pub risk_score: f64,
    pub risk_level: String,
    pub status: String,
    pub details: String,
}

pub const DISPOSABLE_DOMAINS: &[&str] = &[
    "mailinator.com", "guerrillamail.com", "guerrillamailblock.com",
    "sharklasers.com", "grr.la", "guerrillamail.biz", "guerrillamail.de",
    "guerrillamail.info", "guerrillamail.net", "guerrillamail.org",
    "tempmail.com", "throwaway.email", "yopmail.com", "yopmail.fr",
    "yopmail.net", "jetable.org", "jetable.fr", "maildrop.cc",
    "mailnesia.com", "trashmail.com", "trashmail.ws", "tempail.com",
    "10minutemail.com", "temp-mail.org", "dispostable.com",
    "mailcatch.com", "mailexpire.com", "mohmal.com",
    "0-mail.com", "027168.com", "0815.ru", "0815.ry", "0clickemail.com",
    "0w.ro", "10mail.org", "10minutemail.co.za", "10minutemail.nl",
    "123-m.com", "12hosting.nl", "1ce.us", "1chuan.com", "1fsdfdsfsdf.tk",
    "1pad.de", "1st-forms.com", "1usemail.com", "20email.eu", "20mail.eu",
    "20mail.it", "2fdgdfgdfgdf.tk", "2prong.com", "30mail.ir", "33mail.com",
    "3d-painting.com", "4gfdsgfdgfd.tk", "4mail.cf", "4mail.ga",
    "5mail.cf", "5mail.ga", "6mail.cf", "6mail.ga", "6paq.com",
    "7mail.cf", "7mail.ga", "8mail.cf", "8mail.ga", "9mail.cf",
    "9ox.net", "a-bc.net", "a45.in", "abakiss.com", "abcmail.email",
    "abusemail.de", "abyssmail.com", "ac20mail.in", "accamc.com",
    "acentri.com", "adobeccepdm.com", "adpugh.org", "adsd.org",
    "advantimo.com", "afrobacon.com", "ag.us.to", "agedmail.com",
    "agtx.net", "ahk.jp", "airsi.de", "akapost.com", "akerd.com",
    "al-qaeda.com", "aligamel.com", "alisongamel.com", "alldirectbuy.com",
    "allowed.org", "allthegoodnamesaretaken.org", "alph.wtf",
    "amazon-aws.org", "amelabs.com", "amilegit.com", "amiri.net",
    "amiriindustries.com", "ampsylike.com", "anappfor.com",
    "anappthat.com", "andthen.us", "animesos.com", "anit.ro",
    "ano-mail.net", "anonmails.de", "anonymail.dk", "anonymbox.com",
    "anonymized.org", "anonymousness.com", "ansibleemail.com",
    "anthony-junkmail.com", "antireg.com", "antireg.ru", "antispam.de",
    "antispam24.de", "antispammail.de", "apfelkorps.de", "aphlog.com",
    "appc.se", "appinventor.nl", "apps.dj", "arduino.hk", "armyspy.com",
    "aron.us", "artman-conception.com", "arvato-community.de",
    "aschenbrandt.net", "asdasd.nl", "asdasd.ru", "ashleyandrew.com",
    "ass.pp.ua", "astonut.tk", "astroempires.com", "at0mik.org",
    "augmentationtechnology.com", "auti.st", "autorobotica.com",
    "autotwollow.com", "aver.com", "avls.pt", "awatum.de", "axiz.org",
    "azcomputer.org", "badgerland.eu", "badoop.com", "bareed.ws",
    "barryogorman.com", "bartdevos.be", "basscode.org", "bauwerke-online.com",
    "bazaaboom.com", "bcast.ws", "bcb.ro", "bccto.me", "bcooks.com",
    "bdmuzic.pw", "beddly.com", "beefmilk.com", "belljonestax.com",
    "benipaula.org", "bestchoiceusedcar.com", "betr.co", "bgx.ro",
    "bidourlnks.com", "bigprofessor.so", "bigstring.com", "binkmail.com",
    "bio-muesli.info", "bio-muesli.net", "bitymails.us", "blackmarket.to",
    "bladesmail.net", "blip.ch", "blnkt.net", "blogmyway.org",
    "bluedumpling.info", "bluewerks.com", "bobmail.info", "bobmurchison.com",
    "bofthew.com", "bonobo.email", "bookthemmore.com", "bootybay.de",
    "borged.com", "borged.net", "borged.org", "bot.nu", "boun.cr",
    "bouncr.com", "boxformail.in", "boximail.com", "boxtemp.com.br",
    "brailog.com", "breakthru.com", "brefmail.com", "brennendesreich.de",
    "briggsmarcus.com", "broadbandninja.com", "bsnow.net", "bspamfree.org",
    "bspooky.com", "bst-72.com", "btb-notes.com", "btc.email",
    "buffemail.com", "bugfoo.com", "bugmenever.com", "bugmenot.com",
    "bulrushpress.com", "bum.net", "bumpymail.com", "bunchofidiots.com",
    "bund.us", "bundes-li.ga", "burnthespam.info", "burstmail.info",
    "businessbackend.com", "businesssuccessislifesuccess.com",
    "busmail.org", "buymoreplays.com", "buyusedlibrarybooks.org",
    "byebyemail.com", "byespm.com", "bymail.in", "bytesensei.com",
    "caerwyn.com", "calcotel.com", "californiafitnessdeals.com",
    "cam4you.cc", "candymail.de", "car101.pro", "carbtc.net",
    "cars2.club", "carsencyclopedia.com", "casualdx.com", "cavi.mx",
    "cbair.com", "cc.liamria", "cdpa.cc", "ceed.se", "cek.pm",
    "cellurl.com", "centermail.com", "centermail.net", "chacuo.net",
    "chammy.info", "cheaphub.net", "cheatmail.de", "chechnya.conf.work",
    "chickenkiller.com", "chielo.com", "childsavetrust.org",
    "chilkat.com", "chithinh.com", "choicemail1.com", "chong-mail.com",
    "chong-mail.net", "chong-mail.org", "choicemail1.com",
    "cl-cl.org", "cl0ne.net", "clandest.in", "clipmail.eu",
    "clk2020.com", "clk2021.com", "clk2022.com", "closemail.us",
    "cloudns.cx", "cmail.com", "cmail.net", "cmail.org",
    "coldemail.info", "comail2.cf", "compareshippingrates.com",
    "completegolfswing.com", "comwest.de", "conf.work", "consumnerfraud.com",
    "contbay.com", "coolaudio.co", "coolandwacky.us", "coolimpool.org",
    "copitescu.com", "corn2go.com", "correo.blogos.net",
    "cosmorph.com", "courrieltemporaire.com", "coza.ro",
    "crankhole.com", "crapmail.org", "crastination.de",
    "crazymailing.com", "cross-law.ga", "cross-law.gq",
    "cszbl.com", "ctmailing.us", "ctos.ch", "cu.cc",
    "cubiclink.com", "curryworld.de", "cust.in", "cutout.club",
    "cyber-innovation.club", "cyber-phone.eu", "cylab.org",
    "d1yun.com", "d3p.dk", "daabox.com", "dab.ro", "daemsteam.com",
    "daintly.com", "damai.webcam", "dammexe.net", "darkharvestfilms.com",
    "daryxfox.net", "dash-pads.com", "dataarca.com", "datafilehost",
    "datarca.com", "datazo.ca", "davidkoh.net", "davidlcreative.com",
    "dayrep.com", "dbunker.com", "dcemail.com", "ddcrew.com",
    "de-a.org", "deadaddress.com", "deadchildren.org", "deadfake.cf",
    "deadfake.ga", "deadfake.ml", "deadfake.tk", "deadspam.com",
    "deagot.com", "dealja.com", "dealrek.com", "deekayen.us",
    "defomail.com", "degradedfun.net", "delayload.com",
    "delayload.net", "delikkt.de", "delivrmail.com", "demen.ml",
    "dengekibunko.ga", "der-kombi.de", "derkombi.de", "derluxuswagen.de",
    "despam.it", "despammed.com", "dev-null.cf", "dev-null.ga",
    "dev-null.gq", "dev-null.ml", "devnullmail.com", "deyom.com",
    "dfgh.net", "dharmatel.net", "dhm.ro", "dhy.cc", "dialogus.com",
    "diapaulpainting.com", "digitalsanctuary.com", "dildosfromspace.com",
    "dim-coin.com", "dingbone.com", "disaq.com", "disbox.org",
    "discard.cf", "discard.email", "discard.ga", "discard.gq",
    "discard.ml", "discard.tk", "disign-concept.eu", "disign-revelation.com",
    "dispo.in", "dispomail.eu", "disposable-email.ml", "disposable.cf",
    "disposable.ga", "disposable.ml", "disposableemailaddresses.emailmiser.com",
    "dispose.it", "disposeamail.com", "disposemail.com", "dispostable.com",
    "divad.ga", "divermail.com", "dlemail.ru", "dmarc.ro",
    "dndent.com", "dnses.ro", "doanart.com", "dob.jp", "dodgemail.de",
    "dodsi.com", "doiea.com", "dolphinnet.net", "domforfb1.cf",
    "domforfb1.ga", "domforfb1.gq", "domforfb1.ml", "domforfb1.tk",
    "domozmail.com", "donemail.ru", "dongqing365.com", "dontreg.com",
    "dontsendmespam.de", "doquier.tk", "dotman.de", "dotmsg.com",
    "dotslashrage.com", "douchelounge.com", "dozvon-spb.ru",
    "dp76.com", "dr69.site", "drdrb.com", "drdrb.net",
    "droolingfanboy.de", "dropcake.de", "dropjar.com", "droplar.com",
    "dropsin.net", "dsgvo.ru", "dshfjdafd.cloud", "dsmail.dk",
    "duam.net", "duck2.club", "dudmail.com", "duk33.com",
    "dukedish.com", "durandinterstellar.com", "duskmail.com",
    "dwse.edu.pl", "dyceroprojects.com", "dz17.net", "e-mail.com",
    "e-mail.orge-mail.org", "e3z.de", "e4ward.com", "easy-trash-mail.com",
    "easytrashmail.com", "eatmea2z.club", "eay.jp", "ebeschlussbuch.de",
    "ecallheandi.com", "edgex.ru", "edinburgh-airparks.com",
    "edv.to", "ee1.pl", "ee2.pl", "efxs.ca", "egmail.com",
    "einrot.com", "einrot.de", "eintagsmail.de", "elearningjournal.org",
    "electro.mn", "elitevipatlantamodels.com", "email-fake.cf",
    "email-fake.com", "email-fake.ga", "email-fake.gq", "email-fake.ml",
    "email-fake.tk", "email-jetable.fr", "email-temp.com",
    "email.cbes.net", "email.net", "email1.pro", "email60.com",
    "emailage.cf", "emailage.ga", "emailage.gq", "emailage.ml",
    "emailage.tk", "emailate.com", "emailcu.icu", "emaildienst.de",
    "emailfake.com", "emailfake.ml", "emailfreedom.ml", "emailgo.de",
    "emailisvalid.com", "emaillime.com", "emailmiser.com", "emailna.co",
    "emailo.pro", "emailondeck.com", "emailportal.info", "emailproxsy.com",
    "emailresort.com", "emails.ga", "emailsensei.com", "emailsingularity.net",
    "emailspam.co", "emailsy.info", "emailtech.info", "emailtemporanea.com",
    "emailtemporanea.net", "emailtemporar.ro", "emailtemporario.com.br",
    "emailthe.net", "emailtmp.com", "emailto.de", "emailure.net",
    "emailwarden.com", "emailxfer.com", "emailz.cf", "emailz.ga",
    "emailz.gq", "emailz.ml", "emeil.in", "emeil.ir", "emeraldwebmail.com",
    "emil.com", "emkei.cf", "emkei.ga", "emkei.gq", "emkei.ml",
    "emkei.tk", "eml.pp.ua", "emlhub.com", "emlpro.com", "emltmp.com",
    "empireanime.ga", "emstjzh.com", "enayu.com", "enterto.com",
    "envolte.com", "eoffice.top", "eoopy.com", "epb.ro", "epbox.ru",
    "ephemail.net", "ephemeral.email", "eqilux.ga", "ereplyzy.com",
    "ericjohnson.ml", "ero-tube.org", "esadverse.com", "esbano-ru.ru",
    "esc.la", "escapehatchapp.com", "esemay.com", "esgeneri.com",
    "esprity.com", "eth2btc.info", "etheral.email", "ethereum1.top",
    "ethersports.org", "ethor.win", "etotvibor.ru", "euaqa.com",
    "evanfox.info", "evopo.com", "evyush.com", "exdonuts.com",
    "exelica.com", "existiert.net", "exitstageleft.net", "explodemail.com",
    "express.net.ua", "extracurricularsociety.com", "extremail.ru",
    "eyepaste.com", "ez.lv", "ezfill.com", "ezstest.com",
    "f4k.es", "facebook-email.cf", "facebook-email.ga", "facebook-email.ml",
    "facebookmail.gq", "facebookmail.ml", "fackme.gq", "fadingemail.com",
    "faecesmail.me", "fag.wf", "failbone.com", "faithkills.com",
    "fake-box.com", "fake-email.pp.ua", "fake-mail.cf", "fake-mail.ga",
    "fake-mail.ml", "fakedemail.com", "fakedom.com", "fakeinbox.com",
    "fakeinbox.info", "fakemail.fr", "fakemailgenerator.com",
    "fakemailz.com", "fallinhay.com", "fammix.com", "fanclub.com",
    "fangoh.com", "fansworldwide.de", "fantasymail.de", "farrse.co.uk",
    "fast-email.info", "fast-mail.fr", "fastacura.com", "fastchevy.com",
    "fastchrysler.com", "fasternet.biz", "fastkawasaki.com", "fastmazda.com",
    "fastmitsubishi.com", "fastnissan.com", "fastsubaru.com",
    "fastsuzuki.com", "fasttoyota.com", "fastyamaha.com",
    "fatflap.com", "fbma.tk", "fbmail1.ml", "fdn.de", "femailtor.com",
    "fer-gabon.org", "fermaxxi.ru", "fettometern.com", "fexbox.org",
    "fexbox.ru", "fexpost.com", "ficken.de", "fictionsite.com",
    "fightallspam.com", "figjs.com", "figshot.com", "fiifke.de",
    "filbert4u.com", "filberts4u.com", "film-blog.biz", "filzmail.com",
    "findu.pl", "finews.biz", "firemailbox.club", "fivemail.de",
    "fixmail.tk", "flemail.ru", "fliegender.fish", "flowu.com",
    "flu-cc.flu.cc", "flucc.flu.cc", "fluidsoft.us", "fly-ts.de",
    "flyinggeek.net", "flyspam.com", "foobarbot.com", "footard.com",
    "forecastertests.com", "forgetmail.com", "forspam.net",
    "foxja.com", "foxtrotter.info", "fr.nf", "fr33mail.info",
    "fragolina2.tk", "frapmail.com", "frappina.tk", "free-email.cf",
    "free-email.ga", "free-temp.net", "freebabysittercam.com",
    "freeblackbootytube.com", "freecat.net", "freedom4you.info",
    "freedompop.us", "freefattymovies.com", "freelance-france.eu",
    "freeletter.me", "freemail.ms", "freemail.tweakly.net",
    "freemails.cf", "freemails.ga", "freemails.ml", "freemailzone.com",
    "freeplussite.com", "freeschoolgirlvids.com", "freesistercam.com",
    "freeteenbums.com", "freundin.ru", "friendlymail.co.uk",
    "front14.org", "ftp.sh", "ftpinc.ca", "fuckedupload.com",
    "fuckingduh.com", "fuckme69.club", "fucknloveme.top",
    "fuckxxme.top", "fulvie.com", "fun64.com", "funnycodesnippets.com",
    "funnymail.de", "furz.de", "fuvk.ru", "fxnxs.com",
    "fyii.de", "g14l71.com", "g1xmail.top", "g2xmail.top",
    "g3xmail.top", "g4hdrop.us", "gafy.net", "galaxy.tv",
    "gally.jp", "gamail.top", "gamegregious.com", "gamgling.com",
    "garasikita.pw", "garbagecollector.org", "garbagemail.org",
    "gardenscape.ca", "garizo.com", "garliclife.com", "garrymccooey.com",
    "gav0.com", "gbcmail.win", "gbmail.top", "gcmail.top",
    "gdmail.top", "gedmail.top", "geekforex.com", "geew.ru",
    "gehensiemirnichtaufdensack.de", "geldwaschmaschine.de",
    "gelitik.in", "gen.uu.gl", "genderfuck.net", "geronra.com",
    "geschent.biz", "get-mail.cf", "get-mail.ga", "get-mail.ml",
    "get-mail.tk", "get1mail.com", "get2mail.fr", "getairmail.cf",
    "getairmail.com", "getairmail.ga", "getairmail.gq", "getairmail.ml",
    "getairmail.tk", "geteit.com", "getfun.men", "getmails.eu",
    "getnator.com", "getnowtoday.cf", "getonemail.com", "getonemail.net",
    "getover.it", "getsimpleemail.com", "gett.icu", "gexik.com",
    "ggmal.ml", "ghosttexter.de", "giaiphapmuasam.com", "giantmail.de",
    "ginzi.be", "ginzi.co.uk", "ginzi.es", "ginzi.net", "ginzi.nl",
    "ginzi.org", "girlmail.win", "girlsindetention.com", "gishpuppy.com",
    "giveh2o.com", "givmail.com", "glitch.sx", "globaltouron.com",
    "glubex.com", "glucosegrin.com", "gmal.com", "gmeil.me",
    "gmx1mail.top", "gmxmail.top", "gmxmail.win", "gnctr-calgary.com",
    "go2usa.ru", "go2vpn.net", "goemailgo.com", "golemico.com",
    "gomail.in", "gorillaswithdirtybutts.com", "goround.info",
    "gothere.biz", "gotmail.com", "gotmail.net", "gotmail.org",
    "gotti.otherinbox.com", "gowikibooks.com", "gowikicampus.com",
    "gowikicars.com", "gowikifilms.com", "gowikigames.com",
    "gowikimusic.com", "gowikinetwork.com", "gowikionline.com",
    "gowikitravel.com", "gowikitv.com", "grandmamail.com",
    "grandmasmail.com", "great-host.in", "greencafe24.com",
    "greendike.com", "greenhousemail.com", "greensloth.com",
    "greggamel.com", "greggamel.net", "gregorsky.zone", "gregorygamel.com",
    "gregorygamel.net", "grish.de", "griuc.schule", "gs-arc.org",
    "gsredcross.org", "gsxstring.ga", "gudanglowongan.com",
    "guerrillamailblock.com", "gufum.com", "gustr.com", "gwx.de",
    "h8s.org", "habitue.net", "hacccc.com", "hackersquad.org",
    "hackthatbit.ch", "hahawrong.com", "haida-edu.cn", "haltospam.com",
    "hamter.uk", "hangxomcuagon.com", "happydomik.ru", "harakirimail.com",
    "haribu.com", "hartbot.de", "hasanmail.ml", "hat-geld.de",
    "hatespam.org", "hautazi.com", "haydoo.com", "hazelnut4u.com",
    "hazelnuts4u.com", "hccmail.win", "headstrong.de", "heathenhammer.com",
    "heathenhero.com", "hecat.es", "hellodream.mobi", "helloricky.com",
    "helpinghandtax.com", "herp.in", "herpderp.nl", "hi5.si",
    "hiddentragedy.com", "hidebox.org", "hidemail.de", "hidemail.pro",
    "hidemail.us", "hidzz.com", "highbros.org", "hmail.us",
    "hmamail.com", "hmh.ro", "hoanggiaanh.com", "hoanglong.tech",
    "hola.org", "holl.ga", "honor-8.com", "hopemail.biz",
    "hornyalwys.top", "hornyguys.top", "host1s.com", "hostcalls.com",
    "hostgator.top", "hostingmail.me", "hostlaba.com", "hot-mail.cf",
    "hot-mail.ga", "hot-mail.gq", "hot-mail.ml", "hot-mail.tk",
    "hotmai.com", "hotmial.com", "hotprice.co", "housat.com",
    "hpc.tw", "hs.vc", "ht.cx", "huangniu8.com", "hukkmu.tk",
    "hulksales.com", "humaility.com", "humper.info", "hush.ai",
    "hush.com", "hushmail.com", "hushmail.me", "huskion.net",
    "hvastudiesucces.nl", "hwsye.net", "hypenated-domain.com",
    "i2pmail.org", "i6.cloudns.cc", "iaoss.com", "ibnuh.bz",
    "icantbelieveimdoingthis.com", "icx.in", "icx.ro", "idx4.com",
    "ieatspam.eu", "ieatspam.info", "ieh-mail.de", "ige.es",
    "ignoremail.com", "ihazspam.ca", "iheartspam.org", "ikbenspamvrij.nl",
    "illistnoise.com", "ilovespam.com", "imail1.net", "imails.info",
    "imgof.com", "imgv.de", "immo-gerance.info", "imperialcnk.com",
    "imstations.com", "imul.info", "in-ulm.de", "inbax.tk",
    "inbound.plus", "inbox.si", "inbox2.info", "inboxalias.com",
    "inboxbear.com", "inboxclean.com", "inboxclean.org", "inboxdesign.me",
    "inboxed.im", "inboxed.pw", "inboxkitten.com", "inboxproxy.com",
    "inboxstore.me", "inclusiveprogress.com", "incognitomail.com",
    "incognitomail.net", "incognitomail.org", "incq.com",
    "ind.st", "indieclad.com", "indirect.ws", "indomaed.pw",
    "indomina.cf", "indomina.ga", "indomina.gq", "indomina.ml",
    "indomina.tk", "infocom.zp.ua", "ingering.org", "inmynetwork.tk",
    "inoutmail.de", "inoutmail.eu", "inoutmail.info", "inoutmail.net",
];

pub const ROLE_ACCOUNTS: &[&str] = &[
    "admin", "administrator", "webmaster", "postmaster", "hostmaster",
    "info", "support", "help", "contact", "sales", "marketing",
    "noreply", "no-reply", "newsletter", "news", "updates",
    "abuse", "spam", "security", "root", "web", "www",
    "ftp", "mail", "email", "gateway", "daemon", "operator",
    "manager", "service", "billing", "jobs", "careers",
    "hr", "legal", "privacy", "dmca", "unsubscribe",
];
