use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckError {
    pub error_type: String,
    pub description: String,
    pub is_permanent: bool,
    pub solution: Option<String>,
}

impl CheckError {
    pub fn new(error_type: &str, description: &str) -> Self {
        let is_permanent = !TEMPORARY_ERROR_TYPES.contains(&error_type);
        let solution = ERROR_SOLUTIONS.get(error_type).map(|s| s.to_string());
        Self {
            error_type: error_type.to_string(),
            description: description.to_string(),
            is_permanent,
            solution,
        }
    }

    pub fn captcha(description: &str) -> Self {
        Self::new("Captcha", description)
    }

    pub fn bot_protection(description: &str) -> Self {
        Self::new("Bot protection", description)
    }

    pub fn censorship(description: &str) -> Self {
        Self::new("Censorship", description)
    }

    pub fn site_specific(description: &str) -> Self {
        Self::new("Site-specific", description)
    }

    pub fn access_denied(description: &str) -> Self {
        Self::new("Access denied", description)
    }

    pub fn request_blocked(description: &str) -> Self {
        Self::new("Request blocked", description)
    }
}

pub struct ErrorPattern {
    pub pattern: &'static str,
    pub error: CheckError,
}

pub fn get_common_error_patterns() -> Vec<ErrorPattern> {
    vec![
        ErrorPattern {
            pattern: "<title>Attention Required! | Cloudflare</title>",
            error: CheckError::captcha("Cloudflare"),
        },
        ErrorPattern {
            pattern: "<title>Just a moment</title>",
            error: CheckError::bot_protection("Cloudflare challenge page"),
        },
        ErrorPattern {
            pattern: "Please stand by, while we are checking your browser",
            error: CheckError::bot_protection("Cloudflare"),
        },
        ErrorPattern {
            pattern: "<span data-translate=\"checking_browser\">Checking your browser before accessing</span>",
            error: CheckError::bot_protection("Cloudflare"),
        },
        ErrorPattern {
            pattern: "This website is using a security service to protect itself from online attacks.",
            error: CheckError::access_denied("Cloudflare"),
        },
        ErrorPattern {
            pattern: "/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page",
            error: CheckError::bot_protection("Cloudflare challenge redirect"),
        },
        ErrorPattern {
            pattern: "Generated by cloudfront (CloudFront)",
            error: CheckError::request_blocked("Cloudflare"),
        },
        ErrorPattern {
            pattern: "Incapsula incident ID",
            error: CheckError::bot_protection("Incapsula"),
        },
        ErrorPattern {
            pattern: "<title>Client Challenge</title>",
            error: CheckError::bot_protection("Anti-bot challenge"),
        },
        ErrorPattern {
            pattern: "<title>DDoS-Guard</title>",
            error: CheckError::bot_protection("DDoS-Guard"),
        },
        ErrorPattern {
            pattern: "Verifying your browser, please wait...<br>DDoS Protection by</font> Blazingfast.io",
            error: CheckError::bot_protection("Blazingfast"),
        },
        ErrorPattern {
            pattern: "document.getElementById('validate_form_submit').disabled=true",
            error: CheckError::captcha("Mail.ru"),
        },
        ErrorPattern {
            pattern: "\u{0414}\u{043e}\u{0441}\u{0442}\u{0443}\u{043f} \u{043e}\u{0433}\u{0440}\u{0430}\u{043d}\u{0438}\u{0447}\u{0435}\u{043d}</title>",
            error: CheckError::censorship("Rostelecom"),
        },
        ErrorPattern {
            pattern: "\u{0414}\u{043e}\u{0441}\u{0442}\u{0443}\u{043f} \u{043a} \u{0438}\u{043d}\u{0444}\u{043e}\u{0440}\u{043c}\u{0430}\u{0446}\u{0438}\u{043e}\u{043d}\u{043d}\u{043e}\u{043c}\u{0443} \u{0440}\u{0435}\u{0441}\u{0443}\u{0440}\u{0441}\u{0443} \u{043e}\u{0433}\u{0440}\u{0430}\u{043d}\u{0438}\u{0447}\u{0435}\u{043d} \u{043d}\u{0430} \u{043e}\u{0441}\u{043d}\u{043e}\u{0432}\u{0430}\u{043d}\u{0438}\u{0438} \u{0424}\u{0435}\u{0434}\u{0435}\u{0440}\u{0430}\u{043b}\u{044c}\u{043d}\u{043e}\u{0433}\u{043e} \u{0437}\u{0430}\u{043a}\u{043e}\u{043d}\u{0430}",
            error: CheckError::censorship("MGTS"),
        },
        ErrorPattern {
            pattern: "404</h1><p class=\"error-card__description\">\u{041c}\u{044b}&nbsp;\u{043d}\u{0435}&nbsp;\u{043d}\u{0430}\u{0448}\u{043b}\u{0438} \u{0441}\u{0442}\u{0440}\u{0430}\u{043d}\u{0438}\u{0446}\u{0443}",
            error: CheckError::site_specific("MegaFon 404 page"),
        },
        ErrorPattern {
            pattern: "\u{0421}\u{0430}\u{0439}\u{0442} \u{0437}\u{0430}\u{0431}\u{043b}\u{043e}\u{043a}\u{0438}\u{0440}\u{043e}\u{0432}\u{0430}\u{043d} \u{0445}\u{043e}\u{0441}\u{0442}\u{0438}\u{043d}\u{0433}-\u{043f}\u{0440}\u{043e}\u{0432}\u{0430}\u{0439}\u{0434}\u{0435}\u{0440}\u{043e}\u{043c}",
            error: CheckError::site_specific("Site is disabled (Beget)"),
        },
        ErrorPattern {
            pattern: "PerimeterX",
            error: CheckError::bot_protection("PerimeterX"),
        },
        ErrorPattern {
            pattern: "_pxCaptcha",
            error: CheckError::captcha("PerimeterX captcha"),
        },
        ErrorPattern {
            pattern: "/_Incapsula_Resource",
            error: CheckError::bot_protection("Incapsula/Imperva"),
        },
        ErrorPattern {
            pattern: "Request unsuccessful. Incapsula incident ID",
            error: CheckError::request_blocked("Incapsula/Imperva"),
        },
        ErrorPattern {
            pattern: "Access Denied</h1>",
            error: CheckError::access_denied("AWS CloudFront / S3"),
        },
        ErrorPattern {
            pattern: "<title>Access Denied</title>",
            error: CheckError::access_denied("AWS CloudFront / S3"),
        },
        ErrorPattern {
            pattern: "Request was blocked by AWS WAF",
            error: CheckError::request_blocked("AWS WAF"),
        },
        ErrorPattern {
            pattern: "The request could not be satisfied.",
            error: CheckError::request_blocked("AWS CloudFront"),
        },
        ErrorPattern {
            pattern: "Generated by cloudfront (CloudFront)",
            error: CheckError::request_blocked("AWS CloudFront"),
        },
        ErrorPattern {
            pattern: "Reference #",
            error: CheckError::request_blocked("Akamai"),
        },
        ErrorPattern {
            pattern: "Access Denied</h2>You don't have permission to access",
            error: CheckError::access_denied("Akamai"),
        },
        ErrorPattern {
            pattern: "www.google.com/recaptcha/api",
            error: CheckError::captcha("Google reCAPTCHA"),
        },
        ErrorPattern {
            pattern: "g-recaptcha",
            error: CheckError::captcha("Google reCAPTCHA"),
        },
        ErrorPattern {
            pattern: "h-captcha",
            error: CheckError::captcha("hCaptcha"),
        },
        ErrorPattern {
            pattern: "hcaptcha.com",
            error: CheckError::captcha("hCaptcha"),
        },
        ErrorPattern {
            pattern: "funcaptcha.com",
            error: CheckError::captcha("FunCaptcha/Arkose Labs"),
        },
        ErrorPattern {
            pattern: "arkoselabs.com",
            error: CheckError::captcha("FunCaptcha/Arkose Labs"),
        },
        ErrorPattern {
            pattern: "Distil",
            error: CheckError::bot_protection("Distil Networks"),
        },
        ErrorPattern {
            pattern: "Sucuri WebSite Firewall",
            error: CheckError::bot_protection("Sucuri WAF"),
        },
        ErrorPattern {
            pattern: "Access Denied - Sucuri Website Firewall",
            error: CheckError::access_denied("Sucuri WAF"),
        },
        ErrorPattern {
            pattern: "Blocked by StackPath",
            error: CheckError::request_blocked("StackPath"),
        },
        ErrorPattern {
            pattern: "F5 Networks",
            error: CheckError::bot_protection("F5 BIG-IP ASM"),
        },
        ErrorPattern {
            pattern: "The requested URL was rejected",
            error: CheckError::request_blocked("F5 BIG-IP ASM"),
        },
        ErrorPattern {
            pattern: "Barracuda Networks",
            error: CheckError::request_blocked("Barracuda WAF"),
        },
        ErrorPattern {
            pattern: "FortiGuard Web Filtering",
            error: CheckError::request_blocked("Fortinet FortiGuard"),
        },
        ErrorPattern {
            pattern: "Web Application Firewall</title>",
            error: CheckError::bot_protection("Generic WAF"),
        },
        ErrorPattern {
            pattern: "403 Forbidden</title>",
            error: CheckError::access_denied("403 Forbidden"),
        },
        ErrorPattern {
            pattern: "Rate Limit Exceeded",
            error: CheckError::request_blocked("Rate limiting"),
        },
        ErrorPattern {
            pattern: "Too Many Requests",
            error: CheckError::request_blocked("Rate limiting (429)"),
        },
    ]
}

use std::collections::HashMap;
use once_cell::sync::Lazy;

static ERROR_SOLUTIONS: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("Captcha", "Try to switch to another IP address or to use service cookies");
    m.insert("Bot protection", "Try to switch to another IP address or use TLS fingerprinting");
    m.insert("Censorship", "Switch to another internet service provider or use VPN/proxy");
    m.insert("Request timeout", "Try to increase timeout or to switch to another internet service provider");
    m.insert("Connecting failure", "Try to decrease number of parallel connections (e.g. concurrent_limit = 10)");
    m.insert("Access denied", "Try using proxy/VPN or add authorization cookies");
    m.insert("Request blocked", "Try to switch to another IP address or use TLS fingerprinting");
    m.insert("Login required", "Add authorization cookies through cookie jar support");
    m.insert("SSL", "Site may have expired or misconfigured certificate");
    m.insert("Server", "Site server error, try again later");
    m
});

const TEMPORARY_ERROR_TYPES: &[&str] = &[
    "Request timeout",
    "Unknown",
    "Request failed",
    "Connecting failure",
    "HTTP",
    "Proxy",
    "Interrupted",
    "Connection lost",
];

const ERROR_THRESHOLD_PERCENT: f64 = 3.0;

pub fn detect_common_errors(html: &str) -> Option<CheckError> {
    for pattern in get_common_error_patterns() {
        if html.contains(pattern.pattern) {
            return Some(pattern.error);
        }
    }
    None
}

pub fn detect_site_errors(html: &str, site_errors: &HashMap<String, String>) -> Option<CheckError> {
    for (flag, msg) in site_errors {
        if html.contains(flag) {
            return Some(CheckError::site_specific(msg));
        }
    }
    None
}

pub fn detect_error_page(
    html: &str,
    status_code: u16,
    site_errors: &HashMap<String, String>,
    ignore_403: bool,
) -> Option<CheckError> {
    if let Some(err) = detect_site_errors(html, site_errors) {
        return Some(err);
    }

    if let Some(err) = detect_common_errors(html) {
        return Some(err);
    }

    if status_code == 403 && !ignore_403 {
        return Some(CheckError::access_denied("403 status code, use proxy/VPN"));
    }

    if status_code == 999 {
        return None;
    }

    if status_code >= 500 {
        return Some(CheckError::new("Server", &format!("{} status code", status_code)));
    }

    None
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorStats {
    pub error_type: String,
    pub count: usize,
    pub percentage: f64,
    pub is_important: bool,
    pub solution: Option<String>,
}

pub fn extract_and_group_errors(results: &[super::config::PlatformResult]) -> Vec<ErrorStats> {
    let mut error_counts: HashMap<String, usize> = HashMap::new();
    let total = results.len().max(1);

    for r in results {
        if let Some(ref et) = r.error_type {
            *error_counts.entry(et.clone()).or_insert(0) += 1;
        } else if r.error.is_some() {
            *error_counts.entry("Unknown".to_string()).or_insert(0) += 1;
        }
    }

    let mut stats: Vec<ErrorStats> = error_counts
        .into_iter()
        .map(|(err, count)| {
            let percentage = (count as f64 / total as f64) * 100.0;
            let is_important = percentage >= ERROR_THRESHOLD_PERCENT;
            let solution = ERROR_SOLUTIONS.get(err.as_str()).map(|s| s.to_string());
            ErrorStats {
                error_type: err,
                count,
                percentage,
                is_important,
                solution,
            }
        })
        .collect();

    stats.sort_by(|a, b| b.count.cmp(&a.count));
    stats
}
