use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashCrackConfig {
    pub hash: String,
    pub hash_type: String,
    pub wordlist_path: Option<String>,
    pub use_builtin_wordlist: bool,
    pub max_passwords: usize,
    pub timeout: u64,
    pub use_online_lookup: bool,
    pub use_rainbow_table: bool,
    pub use_rule_based: bool,
    pub rainbow_table_path: Option<String>,
}

impl Default for HashCrackConfig {
    fn default() -> Self {
        Self {
            hash: String::new(),
            hash_type: "auto".to_string(),
            wordlist_path: None,
            use_builtin_wordlist: true,
            max_passwords: 10000,
            timeout: 300,
            use_online_lookup: true,
            use_rainbow_table: true,
            use_rule_based: true,
            rainbow_table_path: None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashCrackResult {
    pub success: bool,
    pub found_password: Option<String>,
    pub hash_type_detected: String,
    pub passwords_tried: usize,
    pub time_taken_ms: u64,
    pub summary: String,
    pub attempts: Vec<HashAttempt>,
    pub online_lookup_results: Vec<OnlineLookupResult>,
    pub rainbow_table_results: Vec<RainbowTableResult>,
    pub method_used: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnlineLookupResult {
    pub service: String,
    pub found: bool,
    pub password: Option<String>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RainbowTableResult {
    pub table_name: String,
    pub found: bool,
    pub password: Option<String>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashAttempt {
    pub password: String,
    pub hash: String,
    pub match_found: bool,
}

pub fn get_default_wordlist() -> Vec<String> {
    vec![
        "123456".to_string(),
        "password".to_string(),
        "123456789".to_string(),
        "12345678".to_string(),
        "12345".to_string(),
        "qwerty".to_string(),
        "abc123".to_string(),
        "password1".to_string(),
        "111111".to_string(),
        "123123".to_string(),
        "admin".to_string(),
        "letmein".to_string(),
        "welcome".to_string(),
        "monkey".to_string(),
        "dragon".to_string(),
        "master".to_string(),
        "sunshine".to_string(),
        "qwerty123".to_string(),
        "1q2w3e4r".to_string(),
        "iloveyou".to_string(),
        "princess".to_string(),
        "admin123".to_string(),
        "123456a".to_string(),
        "a123456".to_string(),
        "123abc".to_string(),
        "password123".to_string(),
        "000000".to_string(),
        "888888".to_string(),
        "123321".to_string(),
        "test123".to_string(),
        "1234qwer".to_string(),
        "1234567890".to_string(),
        "121212".to_string(),
        "7777777".to_string(),
        "1234".to_string(),
        "pass".to_string(),
        "666666".to_string(),
        "qwertyuiop".to_string(),
        "123qwe".to_string(),
        "555555".to_string(),
        "asdfgh".to_string(),
        "superman".to_string(),
        "pokemon".to_string(),
        "michael".to_string(),
        "1234567".to_string(),
        "shadow".to_string(),
        "football".to_string(),
        "123456789a".to_string(),
        "root".to_string(),
        "toor".to_string(),
        "test".to_string(),
        "guest".to_string(),
        "user".to_string(),
        "demo".to_string(),
        "default".to_string(),
        "changeme".to_string(),
        "secret".to_string(),
        "trustno1".to_string(),
        "access".to_string(),
        "hello".to_string(),
        "charlie".to_string(),
        "donald".to_string(),
        "batman".to_string(),
        "robert".to_string(),
        "jordan".to_string(),
        "hunter".to_string(),
        "hunter2".to_string(),
        "pepper".to_string(),
        "daniel".to_string(),
        "thomas".to_string(),
        "george".to_string(),
        "andrew".to_string(),
        "matrix".to_string(),
        "freedom".to_string(),
        "whatever".to_string(),
        "qazwsx".to_string(),
        "trustme".to_string(),
        "ninja".to_string(),
        "mustang".to_string(),
        "jessica".to_string(),
        "starwars".to_string(),
        "ashley".to_string(),
        "abcdef".to_string(),
        "654321".to_string(),
        "zxcvbn".to_string(),
        "password!".to_string(),
        "p@ssw0rd".to_string(),
        "P@ssw0rd".to_string(),
        "p@ssword".to_string(),
        "passw0rd".to_string(),
        "Passw0rd".to_string(),
        "pa$$word".to_string(),
        "letmein!".to_string(),
        "admin!".to_string(),
        "root123".to_string(),
        "root@123".to_string(),
        "Admin123".to_string(),
        "Admin@123".to_string(),
        "qwer1234".to_string(),
        "asdf1234".to_string(),
        "zxcv1234".to_string(),
        "1qaz2wsx".to_string(),
        "1qaz@WSX".to_string(),
        "zaq1xsw2".to_string(),
        "!QAZ2wsx".to_string(),
        "qweasdzxc".to_string(),
        "1234abcd".to_string(),
        "abcd1234".to_string(),
        "test1234".to_string(),
        "temp1234".to_string(),
        "spring".to_string(),
        "summer".to_string(),
        "autumn".to_string(),
        "winter".to_string(),
        "baseball".to_string(),
        "soccer".to_string(),
        "hockey".to_string(),
        "basketball".to_string(),
        "tennis".to_string(),
        "yankees".to_string(),
        "jordan23".to_string(),
        "liverpool".to_string(),
        "arsenal".to_string(),
        "chelsea".to_string(),
        "killer".to_string(),
        "phoenix".to_string(),
        "camaro".to_string(),
        "chevy".to_string(),
        "corvette".to_string(),
        "ferrari".to_string(),
        "porsche".to_string(),
        "mercedes".to_string(),
        "toyota".to_string(),
        "honda".to_string(),
        "apple".to_string(),
        "google".to_string(),
        "facebook".to_string(),
        "twitter".to_string(),
        "instagram".to_string(),
        "amazon".to_string(),
        "microsoft".to_string(),
        "samsung".to_string(),
        "oracle".to_string(),
        "mysql".to_string(),
        "postgres".to_string(),
        "redis".to_string(),
        "mongodb".to_string(),
        "server".to_string(),
        "backup".to_string(),
        "network".to_string(),
        "system".to_string(),
        "service".to_string(),
        "support".to_string(),
        "info".to_string(),
        "webmaster".to_string(),
        "manager".to_string(),
        "operator".to_string(),
        "monitor".to_string(),
        "control".to_string(),
        "manager123".to_string(),
        "supervisor".to_string(),
        "administrator".to_string(),
        "sa".to_string(),
        "sysadmin".to_string(),
        "dba".to_string(),
        "postgres123".to_string(),
        "mysql123".to_string(),
        "redis123".to_string(),
        "oracle123".to_string(),
        "testuser".to_string(),
        "testadmin".to_string(),
        "dev".to_string(),
        "dev123".to_string(),
        "developer".to_string(),
        "deploy".to_string(),
        "staging".to_string(),
        "production".to_string(),
        "jenkins".to_string(),
        "gitlab".to_string(),
        "docker".to_string(),
        "kubernetes".to_string(),
        "ansible".to_string(),
        "terraform".to_string(),
        "ubuntu".to_string(),
        "centos".to_string(),
        "debian".to_string(),
        "fedora".to_string(),
        "redhat".to_string(),
        "linux".to_string(),
        "raspberry".to_string(),
    ]
}
